### ISSUE TITLE
Compile to Scala3

### ISSUE THREAD

**Issue by pepegar** [higherkindness/droste#193]
It would be great to start working on making Droste compile to Scala3

**Comment by TimWSpence** [comment]
I don't know how anyone else feels but I would be very happy with an initial scala 3 release with no macro support - I can cope with writing the corresponding base functors by hand for the moment, especially if we can get kittens for scala 3 over the line so that `Functor` and `Traversable` instances are derivable

**Comment by Daenyth** [comment]
I have a work in progress branch on that; https://github.com/higherkindness/droste/tree/gb-scala3

**Comment by juanpedromoreno** [comment]
Thanks @Daenyth , [this has been completed now](https://github.com/higherkindness/droste/releases/tag/v0.9.0-M3) 🎉 !
